update ping probe
oversight/pingprobe pull request #2
Opened 2022-03-09 14:18 UTC by AnjaBruls

## Description

First update to the ping probe.

2022-03-11 07:40 UTC, joente commented on lib/check/base.py
> +            asset_id = data['hostUuid']  # TODO remove?
If not used, maybe comment the line. It still might be useful to quickly know how to get the asset_id

2022-03-11 07:41 UTC, joente commented on lib/check/base.py
> +            logging.exception(f'Ping error: `{err}`\n')
The address might be useful in the exception, is this provided by the `err` variable of do you need to add the `address` to the log line?

2022-03-11 07:41 UTC, joente commented on lib/check/base.py
> +            logging.exception('Ping parse error\n')
At least add the `address` as otherwise you have no clue which address was being pinged

2022-03-11 07:43 UTC, joente requested changes
I think that only the exceptions need to be improved

2022-03-14 09:47 UTC, AnjaBruls commented on lib/check/base.py
> +            asset_id = data['hostUuid']  # TODO remove?
see [623fb06](https://github.com/oversight/pingprobe/pull/2/commits/623fb0643592eb1e8f1626e000e922e5255b121a)

2022-03-14 09:49 UTC, AnjaBruls commented on lib/check/base.py
> +            logging.exception(f'Ping error: `{err}`\n')
I added the address to the log line. See [623fb06](https://github.com/oversight/pingprobe/pull/2/commits/623fb0643592eb1e8f1626e000e922e5255b121a)

2022-03-14 09:49 UTC, AnjaBruls commented on lib/check/base.py
> +            logging.exception('Ping parse error\n')
I added the address to the log line. See [623fb06](https://github.com/oversight/pingprobe/pull/2/commits/623fb0643592eb1e8f1626e000e922e5255b121a)

2022-03-15 10:42 UTC, joente commented on lib/check/base.py
> -    interval = 300
This `interval` is not the same interval as parsed to the ping check. The "interval" for the ping check is the interval between each ping. This "interval" is the interval between each time to perform the check.

2022-03-15 10:54 UTC, joente approved these changes

2022-03-15 10:55 UTC, merged